baseURL = "http://example.org/"
languageCode = "ja"
languageName = "Japan"
theme = "LoveIt"
title = "gegeson's portfolio"

[author]
email = "yushin1301@gmail.com"
link = "/about/about_me"
name = "Yuki Shigemasa"

[markup]
# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

[menu]
[[menu.main]]
identifier = "posts"
weight = 1
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
name = "Posts"
post = ""
url = "/posts/"
# title will be shown when you hover on this menu link
title = ""
[[menu.main]]
identifier = "tags"
name = "Tags"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "categories"
name = "Categories"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3
# [[menu.main]]
# identifier = "about"
# name = "About"
# post = ""
# pre = ""
# title = ""
# url = "/about/"
# weight = 4
[[menu.links]]
identifier = "github"
name = "GitHub"
pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
url = ""
weight = 0

[params.social]
github = "gegeson"
instagram = "masayuki_shige"
linkedin = "yuki-shigemasa-99b26a1b6"
twitter = "gegesonyushin"

# Header config
[params.header]
desktopMode = "fixed"
mobileMode = "auto"
[params.header.title]
logo = ""
name = "gegeson's portfolio"
post = ""
pre = ""
typeit = false

# Footer config
[params.footer]
enable = true
# LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
custom = ''
# LoveIt NEW | 0.2.0 whether to show Hugo and theme info
hugo = true
# LoveIt NEW | 0.2.0 whether to show copyright info
copyright = true
# LoveIt NEW | 0.2.0 whether to show the author
author = true
# Site creation time
since = 2019
# ICP info only in China (HTML format is supported)
icp = ""
# license info (HTML format is supported)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# LoveIt NEW | 0.2.0 Section (all posts) page config
[params.section]
# special amount of posts in each section page
paginate = 20
# date format (month and day)
dateFormat = "01-02"
# amount of RSS pages
rss = 10

# LoveIt NEW | 0.2.0 List (category or tag) page config
[params.list]
# special amount of posts in each list page
paginate = 20
# date format (month and day)
dateFormat = "01-02"
# amount of RSS pages
rss = 10

# LoveIt NEW | 0.2.0 App icon config
[params.app]
# optional site title override for the app when added to an iOS home screen or Android launcher
title = "My cool site"
# whether to omit favicon resource links
noFavicon = true
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = ""
# Android browser theme color
themeColor = "#ffffff"
# Safari mask icon color
iconColor = "#5bbad5"
# Windows v8-10 tile color

tileColor = "#da532c"

# LoveIt NEW | 0.2.0 Search config
[params.search]
absoluteURL = false
contentLength = 4000
enable = true
highlightTag = "em"
maxResultLength = 10
placeholder = ""
snippetLength = 30
type = "lunr"

[params.search.algolia]
appID = ""
index = ""
searchKey = ""

# Home page config
[params.home]
# LoveIt NEW | 0.2.0 amount of RSS pages
rss = 10
# Home page profile
[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = "/images/logo.png"
# LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
title = ""
# subtitle shown in home page (HTML format is supported)
subtitle = "Hi, I'm Yuki Shigemasa."
# whether to use typeit animation for subtitle
typeit = true
# whether to show social links
social = true
# LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
disclaimer = ""
# Home page posts
[params.home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 6
# LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
# default behavior when you don't set "hiddenFromHomePage" in front matter
defaultHiddenFromHomePage = false

[outputs]
home = ["HTML", "RSS", "JSON"]
